=== AnastasiyaZaitsava/TATJAVA01_2017_Task05_Anastasiya_Zaitsava/MenuSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/MenuSchema" 
	xmlns:tns="http://www.example.org/MenuSchema">
	<element name = "Menu">
	<complexType>
	<sequence>
		<element name = "Section" maxOccurs = "unbounded">
			<complexType mixed="true">
			<sequence>
				<element name = "food" maxOccurs = "unbounded">
				<complexType>
				<sequence>
					<element name = "name" type = "string"/>
					<element name = "description" type = "string" minOccurs = "0" maxOccurs = "unbounded"/>
					<element name = "portion" type = "string"/>
					<element name = "price" type = "int" minOccurs = "0" maxOccurs = "unbounded"/>
				</sequence>
				<attribute name = "ID" type = "string"/>
				</complexType>
				</element>
			</sequence>
			<attribute name = "SectionName" type = "string"/>
			</complexType>
		</element>
	</sequence>
	</complexType>
	</element>
</schema>

=== AnastasiyaZaitsava/TATJAVA01_2017_Task05_Anastasiya_Zaitsava/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<Menu xmlns:tns="http://www.example.org/MenuSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/MenuSchema MenuSchema.xsd ">
  <Section SectionName = "Холодные закуски">
    <food ID = "1">
      <name>Ассорти рыбное</name>
      <description>Слабосоленая форель, семга</description>
      <portion>100/20/15</portion>
    </food>
    <food ID = "2">
      <name>Куриный рулет</name>
      <description>Куриный рулет собственного производства</description>
      <portion>100/5</portion>
    </food>
    <food ID = "3">
      <name>Лимон</name>
      <portion>60</portion>
    </food>
  </Section>
  
  <Section SectionName = "Горячие закуски">
    <food ID = "1">
      <name>Лобио с шампиньонами</name>
      <description>Фасоль с шампиньонами и грецким орехом</description>
      <portion>150/5</portion>
      <price>105</price> 
    </food>
    <food ID = "2">
      <name>Жульен</name>
      <description>1. С курицей</description>
      <description>2. С грибами</description>
      <portion>120/1</portion>
      <price>145</price>
      <price>155</price>
    </food>
  </Section>
</Menu>
